### PR TITLE
Issue #13: fix cast exception on throws rule

### LINKED ISSUE #13: ETO-304: 'DoEarlyReturnWhenPossible' rule throws an unexpected cast Exception on some cases
# Error's description
`java.lang.ClassCastException: class org.sonar.java.model.statement.ThrowStatementTreeImpl cannot be cast to class org.sonar.plugins.java.api.tree.BlockTree`

This error occurs when the rule is analyzing a piece of code, which has a conditional ‘else’ statement that consists of a single expression, instead of a block of code (enclosed in braces).

The rule tries to convert the ‘else’ statement into a block of code every time, and throws an error when the cast is unsuccessful.

# Steps to reproduce the error
1. In the `etendo_sonar_java_plugin` repository folder, go to the `src/test/resources/DoEarlyReturnWhenPossible.java` test resources file.
2. Add the following code, this will be the bug’s test case:
```
/*
  `getReport` method from `InfComision` class. Found in 'Drivania' project. Testing rule's behaviour when the conditional 'else'
  statement to be analyzed is a single expression, instead of a block of code (enclosed in braces)
 */
private String getReport(ConnectionProvider cp, VariablesSecureApp vars, String strDateFrom, String strDateTo,
    String strcBpartnerId, String strOrg, String strAgentId) throws Exception {
  String partner = (strcBpartnerId == null || strcBpartnerId.isEmpty()) ? null : strcBpartnerId;
  String agent = (strAgentId == null || strAgentId.isEmpty()) ? null : strAgentId;
  String org = (strOrg == null || strOrg.isEmpty()) ? null :   strOrg;

  PrintInvoicesData[] data = null;
  if(null!= agent) {
    return agent;
  }else {
    data = PrintInvoicesData.getAgentConPartner(cp, strDateFrom, strDateTo, partner, org );
  }
  if (0 != data.length) {
    String result = "";
    for (int i = 0; i < data.length; i++) {
      result = result + data[i].agent + ",";
    }
    return result;
  }else // Noncompliant
    throw new Exception("No hay datos.");
}
```
3. Run the `DoEarlyReturnWhenPossibleTest` test.
4. The test will fail for this case.

# Expected behavior
The test should pass correctly.

# Affected Version
`etendo_sonar_java_plugin` → `Version 1.0.1`

# Solution Design
* In the `StatementUtils` class, in the `statementHandlesInitialErrorCondOnElse` method, instead of directly casting the `elseStatement` variable to `BlockTree`, first check if it is an instance of  `Tree.Kind.THROW_STATEMENT`. If so, this means that the else statement consists of a single 'throw' statement. return true if this is the case, as this means that the else statement is handling an initial error condition.
* Else, if the statement is a block statement (`Tree.kind.BLOCK_STATEMENT`), then it can be safely casted to `BlockTree`. Maintain the logic for this case

### PR DESCRIPTION
**Pull request by facumoyanosmf**
ETO-304

### CODE REVIEW

File: src/test/resources/DoEarlyReturnWhenPossible.java [hunk 1]
```diff
@@ -43,4 +43,30 @@ public String getValue(Element parentElem, String name, boolean mandatory) { //
...
+    statement to be analyzed is a single expression, instead of a block of code (enclosed in braces)
+   */
+  private String getReport(ConnectionProvider cp, VariablesSecureApp vars, String strDateFrom, String strDateTo,
+      String strcBpartnerId, String strOrg, String strAgentId) throws Exception {
+    String partner = (strcBpartnerId == null || strcBpartnerId.isEmpty()) ? null : strcBpartnerId;
+    String agent = (strAgentId == null || strAgentId.isEmpty()) ? null : strAgentId;
+    String org = (strOrg == null || strOrg.isEmpty()) ? null :   strOrg;
+
+    PrintInvoicesData[] data = null;
+    if(null!= agent) {
```
Comment (Gremiger) [inline src/test/resources/DoEarlyReturnWhenPossible.java]: This doesn't have the [Etendo code style](https://docs.etendo.software/latest/developer-guide/etendo-classic/getting-started/installation/intellij-code-formatting/?h=code+style)

**Review by Gremiger — CHANGES_REQUESTED** [review]

**Review by RubenEtendo — APPROVED** [review]

**Review by valeg-etendo — APPROVED** [review]

**Review by Gremiger — APPROVED** [review]

File: src/test/resources/DoEarlyReturnWhenPossible.java [hunk 2]
```diff
@@ -43,4 +43,30 @@ public String getValue(Element parentElem, String name, boolean mandatory) { //
...
+      data = PrintInvoicesData.getAgentConPartner(cp, strDateFrom, strDateTo, partner, org);
+    }
+    if (0 != data.length) { // Noncompliant
+      String result = "";
+      for (int i = 0; i < data.length; i++) {
+        result = result + data[i].agent + ",";
+      }
+      return result;
+    } else
+      throw new Exception("No hay datos.");
```
Comment (RomanMagnoli) [inline src/test/resources/DoEarlyReturnWhenPossible.java:70]: Should be in English. Also, throwing a generic exception is not a good practice.

**Review by RomanMagnoli — CHANGES_REQUESTED** [review]

File: src/test/resources/DoEarlyReturnWhenPossible.java (hunk 2 above)
Comment (facumoyanosmf) [reply src/test/resources/DoEarlyReturnWhenPossible.java:70]: @RomanMagnoli this method was taken from the "Drivania" project, it is a test case that checks the plugin in the "DoEarlyReturnWhenPossible" test.

**Review by valenvivaldi — APPROVED** [review]

**Review by RomanMagnoli — APPROVED** [review]
